jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.4/bazel-0.1.4-installer-linux-x86_64.sh'
  - chmod +x 'bazel-0.1.4-installer-linux-x86_64.sh'
  - ./bazel-0.1.4-installer-linux-x86_64.sh --user

script:
  - bazel run data_structures:demo
