jdk:
  - oraclejdk8

compiler:
  - gcc

addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
      - pkg-config
      - zip
      - zlib1g-dev
      - unzip
      - wget
      - zlib1g-dev

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.4/bazel-0.1.4-installer-linux-x86_64.sh'
  - chmod +x 'bazel-0.1.4-installer-linux-x86_64.sh'
  - ./bazel-0.1.4-installer-linux-x86_64.sh --user

script:
  - /usr/bin/gcc --version
  - gcc --version
  - bazel build ...
    #- bazel build --verbose_failures --spawn_strategy=standalone --genrule_strategy=standalone data_structures:demo
