jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip
      - gcc-4.8
      - g++-4.8
      - wget
      - openjdk-7-jdk
      - openjdk-7-source
      - pkg-config
      - zip
      - zlib1g-dev

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.4/bazel-0.1.4-installer-linux-x86_64.sh'
  - chmod +x 'bazel-0.1.4-installer-linux-x86_64.sh'
  - ./bazel-0.1.4-installer-linux-x86_64.sh --user

script:
  - bazel build --spawn_strategy=standalone --genrule_strategy=standalone data_structures:demo
